// <auto-generated />
using FoodCompositionScraper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodCompositionScraper.Migrations
{
    [DbContext(typeof(FoodContext))]
    [Migration("20250204151405_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("FoodCompositionScraper.Models.FoodData", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("FoodCompositionScraper.Models.FoodDataComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaximumValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MinimumValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumberSamples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StandardDeviation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValuePer100g")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodCode");

                    b.ToTable("FoodDataComponent");
                });

            modelBuilder.Entity("FoodCompositionScraper.Models.FoodDataComponent", b =>
                {
                    b.HasOne("FoodCompositionScraper.Models.FoodData", "FoodData")
                        .WithMany("Components")
                        .HasForeignKey("FoodCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodData");
                });

            modelBuilder.Entity("FoodCompositionScraper.Models.FoodData", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
